project:
  type: website
  output-dir: docs

website:
  title: ""
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - blog.qmd
      - cooking.qmd
      - basketball.qmd
      

format:
  html:
    theme: minty
    css: styles.css
    toc: true
    page-layout: full

editor: visual

