---
title: "About Me"
format: html
---

### 🚀

Hello! My name is Maxwell Patterson, and I'm currently working at Zora Ecosystems, a nature restoration company in London, where I apply data science to support ecosystem restoration and environmental impact. I'm passionate about using data-driven approaches to tackle environmental challenges and contribute to a more sustainable future.

### 🌲

My work in environmental data science is fueled by my strong interest in climate communication, data visualization, and sustainability. I believe that effective communication is crucial in driving positive change, and I'm dedicated to presenting complex environmental data in clear and impactful ways.

### 👨‍🍳

Beyond my academic pursuits, I have a deep love for cooking. In fact, I took my passion to the next level by attending culinary school at the prestigious Le Cordon Bleu, where I earned a French Cuisine Certificate SCQF Level 6. Through this experience, I honed my culinary skills, learned classic French techniques, and developed a greater appreciation for the art of cooking. I find joy in experimenting with different flavors, creating delightful dishes, and sharing my culinary creations with others.

### 🔢🤽‍♂️

I hold a Bachelor of Arts in Applied Mathematics-Economics from Brown University, where I also had the privilege of being a member of the varsity water polo team. As a four-time Academic All-American and the 2022 Team Captain, I learned valuable lessons in leadership, teamwork, and perseverance. I went on to earn a Master's degree in Environmental Data Science (MEDS) from the Bren School of Environmental Science & Management at the University of California, Santa Barbara (UCSB), where I deepened my expertise in applying data-driven approaches to environmental challenges.

### 🗺️

Through this blog, I aim to share my experiences, insights, and projects related to environmental data science, climate communication, and beyond. I'm excited to connect with like-minded individuals, exchange ideas, and contribute to the growing community of data-driven environmentalists. Join me on this journey as we explore the power of data in shaping a more sustainable world!
